### ISSUE TITLE
How to switch to BGR?

### ISSUE THREAD

**Issue by Kampi** [fbiego/esp32-lvgl-watchface#1]
I want to port this project for our [Smartwatch project](https://github.com/jakkra/ZSWatch) and I need BGR format. I have changed the code in line `628` and `677`

```
val abgr = (alpha shl 24) or (b shl 16) or (g shl 8) or r
val rgb565WithAlpha = (alpha shl 16) or (blue shl 11) or (green shl 5) or red
```

The preview image is BGR, but the LVGL code doesn´t work with BGR enabled. Do I miss something?

**Comment by fbiego** [comment]
With this project, i'm using 16bit swapped. If you are not using swapped then you might need to change the following lines

https://github.com/fbiego/esp32-lvgl-watchface/blob/fe7637580ecea3ac9343038d6ec4d473fb56ab7f/src/faces/bin2lvgl.kt#L679-L681

to

```
// Big Endian format
byteArray += ((rgb565WithAlpha shr 8) and 0xFF).toByte()
byteArray += (rgb565WithAlpha and 0xFF).toByte()
```
https://github.com/fbiego/esp32-lvgl-watchface/blob/fe7637580ecea3ac9343038d6ec4d473fb56ab7f/src/faces/bin2lvgl.kt#L843-L845

to

```
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 for watchfaces"
#endif
```
